# Generated by Django 4.2.6 on 2023-10-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_solicitacaoexame_pedidosexames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidosExames',
        ),
    ]
